# Generated by Django 5.1.6 on 2025-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_dcmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarvelModel',
        ),
    ]
